### PR TITLE
Remove text prediction feature for now

### PR DESCRIPTION
**Pull request by dobey**
As presage has been unmaintained since 2018, among various other concerns with
the feature and how the ngram databases are created, remove text prediction for
now until a better implementation can be done, after keyboard layouts support
has been refactored to be much simpler.

### CODE REVIEW

**Comment by dobey** [comment]
Also, maybe @sunweaver might have an opinion on this, as he's maintaining the packages in Debian for maliit now. Would be good for some feedback there.

**Comment by sunweaver** [comment]
As we want to replace lomiri-keyboard by maliit-keyboard in Ubuntu Touch 22.04, this feature will probably dearly be missed. For Debian, it is not so relevant, because people will never have used the presage feature in a Debian stable release.

Also, presage is in maintenance-only mode in Debian, as well: https://metadata.ftp-master.debian.org/changelogs//main/p/presage/presage_0.9.1-2.2_changelog

**Comment by sunweaver** [comment]
@mariogrip @peat-psuwit ^^^

**Comment by dobey** [comment]
> As we want to replace lomiri-keyboard by maliit-keyboard in Ubuntu Touch 22.04, this feature will probably dearly be missed. For Debian, it is not so relevant, because people will never have used the presage feature in a Debian stable release.

It worked quite poorly and it is something people commonly turn off as soon as they start using Ubuntu Touch. However, word completion with spell checking via hunspell is still working fine, if the dictionary for the language is installed.

**Comment by mikhas** [comment]
When we first implemented word candidates it was always assumed that a better (free!) predication would materialize eventually. I guess that didn't happen so then the whole feature should be dropped...

**Review by KAMiKAZOW — DISMISSED** [review]

**Comment by KAMiKAZOW** [comment]
I do have a merge button now but I these changes are above my skill level to actually judge. I would need confirmation of eg. @evelikov that this still builds and breaks nothing else. I'm also not an owner of this organization, so I cannot elevate eg. someone from the SteamOS developers to (hopefully) maintain Maliit.

**Comment by sunweaver** [comment]
@dobey please let us know if you are still upstream for maliit-keyboard + framework. Personally, I have been in touch with Rodney on Maliit issues in Debian + Ubuntu. So, he is around and also using Maliit.

**Comment by KAMiKAZOW** [comment]
> That said, I'm not sure what you mean with "to elevate"? If the project is no longer maintained, the README should really be updated to reflect that.

To clarify: I have commit access because I write reasonable release notes when someone of the actual developers prepares a release. I'm not and never been in regular contact with any of them.

**Comment by dobey** [comment]
> Currently we disable hunspell/spell checker, when presage is off 😱

I don't see anything suggesting so in the code. They are separate settings, and separate properties in language plugins. I've also tested the change fairly heavily with hunspell still working.

> Will prep an updated PR later today, unless someone beats me to it.

These references were all ineffectual, but I've removed them in this PR now as well.

**Pull request merged**
