### PR TITLE
Bring back LanguagePluginInterface

### PR DESCRIPTION
**Pull request by mariogrip**
Without this maliit-server is unable to cast the language plugin causing
a segfault rendering maliit-server non functional.

This partly reverts commit 1e5aa06d579fcd65fb6640b23b70318386ba3564.

### CODE REVIEW

**Comment by mariogrip** [comment]
ping @jpetersen :)

**Comment by jpetersen** [comment]
I do not see directly why it would crash without the patch, I will need another look.

**Comment by mariogrip** [comment]
> I do not see directly why it would crash without the patch, I will need another look.

It fails to cast as it cant figure out the interface. It might be able to fudge it in other ways, but this fixed the issue we had on manjaro to get keyboard to load using maliit-server. It works using the built in keyboard binary. so problem is when it tries to load it as a plugin, where the interface is needed.

**Comment by jpetersen** [comment]
Ok let us merge.

**Pull request merged**
