### PR TITLE
Fix #39

### LINKED ISSUE #39: Chinese (Pinyin): Properly handle partial suggestion words
On master

1. Switch language to zh-hans
2. Type `miaowu`
3. Press on any single character
4. Press Backspace

Observed:
in 3: the single character is inputted.
in 4: the character is removed.

Expected (ideal):
in 3: selected character kept in a buffer, displayed on the left. Suggestion list should be for the remaining input. For the example video, the buffer should be `喵wu`, and suggestions be those for `wu`.
in 4: return to the state just after 2. i.e. the Backspace serves roughly the same as an undo.

Video:
https://tusooa.xyz/_matrix/media/r0/download/tusooa.xyz/wPSiRWcURuzdzGkqFFLTrtHb

### PR DESCRIPTION
**Pull request by tusooa**

### CODE REVIEW

**Comment by tusooa** [comment]
> in 3: selected character kept in a buffer, displayed on the left. Suggestion list should be for the remaining input. For the example video, the buffer should be 喵wu, and suggestions be those for wu.

For this, I used a workaround to make the partially converted string *the first candidate* in the list. Which may or may not be favourable. 

> in 4: return to the state just after 2. i.e. the Backspace serves roughly the same as an undo.

This has the same problem as in https://github.com/maliit/keyboard/issues/38, and is out of scope of this MR.

**Comment by tusooa** [comment]
Video demo:

https://tusooa.xyz/_matrix/media/r0/download/tusooa.xyz/YgUOVGAMiFyRphYJpifpEnDs

**Comment by tusooa** [comment]
I guess this is okay for now.

**Comment by KAMiKAZOW** [comment]
Looks cool.

Just curious: Is typing radicals instead of Latin letters a thing in Chinese?

**Comment by tusooa** [comment]
It is, and was a popular way of inputting on old phones. But it is not the Pinyin input method.

________________________________

**Comment by KAMiKAZOW** [comment]
How about merging all three open PRs and then release a new version (2.0.1 or so), @jpetersen?

**Review by jpetersen — APPROVED** [review]

**Pull request merged**
