### PR TITLE
Update COPYING.CC-BY

### PR DESCRIPTION
**Pull request by KAMiKAZOW**
Update to 4.0, matching Lomiri's Weblate. Possible according to https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses which also explicitly notes that 4.0 is compatible with GPL 3.0.

### CODE REVIEW

**Review by dobey — CHANGES_REQUESTED** [review]
I don't think this is right. We would need to get permissions from all contributors of artwork, to change the license to 4.0 from 3.0. And there's no reason for us to do that.

I'm not sure what you mean about Lomiri's Weblate here, either.

**Comment by KAMiKAZOW** [comment]
Didn't you merge those?

image

https://translate.ubports.com/projects/ubports/lomiri-keyboard/

**Comment by KAMiKAZOW** [comment]
Someone at UBPorts attached the 4.0 tag to the English original (which is wrong) and then made translators think that their contributions are 4.0 as well but the git repo still had the original license. I don't know who messed up there but it's now a licensing conflict. https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses says nothing about asking people.

**Comment by dobey** [comment]
> Didn't you merge those?

They were merged from git, and Weblate itself doesn't alter the license comment in the po files, so I wasn't aware of any CC-By-SA, and I'm not sure any translators are even aware of what it means. Also, all of the translations cannot be CC-By-SA, because they are not all originated from the weblate (and weblate cannot re-license existing translations which were imported from the git repo initially). Furthermore, CC-By-SA doesn't really even make sense for translations, because strings get edited over time by multiple people. Requiring attribution displayed in the app for every little edit is untenable.

> says nothing about asking people.

You cannot just take something licensed under one license, and then re-license it to another license, without the permission of the copyright holder. It doesn't need to say that in the license, because it's how copyright law works. This is why every release blog post for maliit has the section at the bottom asking for help to get Canonical to relicense all their code back to BSD.

**Comment by KAMiKAZOW** [comment]
> You cannot just take something licensed under one license, and then re-license it to another license, without the permission of the copyright holder.

If the license allows upgrading, that is already explicit permission to license to a different version. I've liked to a page on creativecommons.org. For example if software merely says "License: GPL", it means any version of the GPL. The license text is 100% clear about that,

> This is why every release blog post for maliit has the section at the bottom asking for help to get Canonical to relicense all their code back to BSD.

Yeah, I wrote that, just as I wrote the rest of the 2.0 announcement. I know what I wrote.

Personally, I don't care much which CC version is used, I just don't want yet another license in the mix. Canonical's LGPL-3.0-ONLY code is more than enough in the mix.

**Comment by dobey** [comment]
> If the license allows upgrading,

That is a choice of the copyright holder, not the license. What you've said here isn't how things work. Nobody just says "any version of GPL" or "any CC license" when they create software or artwork. They license things under specific versions. New versions would require the copyright holder to release the said software or artwork under the new version, unless they've already explicitly said "or any later version." And nobody ever says "or any earlier version."

> Personally, I don't care much which CC version is used,

The existing CC 3.0 is for _artwork_ not translations, and has been there for 8 years..

> I just don't want yet another license in the mix. 

Then the solution is to remove what might be under said new license, which in this case would mean manually going through and reverting by hand (because attempting to script it just fails), all commits that came from the Weblate. I would also be fine with removing the remaining files under COPYING.CC-BY, which I believe is only the wav file for key press audio feedback at this point.

**Comment by KAMiKAZOW** [comment]
> That is a choice of the copyright holder, not the license.

That's what the copyright holder allowed when they picked the license, duh.

> So this change is just wrong. and I'll close it on that basis.

Whatever but please fix the mess you created when importing translations that were under a wrong license which, by your own account, is not allowed. UBPorts tagged the sources as 4.0, then people contributed under that assumption.

**Comment by dobey** [comment]
> That's what the copyright holder allowed when they picked the license, duh.

There is no need for you to be rude. It is not what the copyright holder allowed. They picked a specific version of a license, not "or any later." If you really want to have it out with someone, go to London and tell the General Counsel for Canonical "duh" and see what happens.

> Nope. That's neither what the GPL says nor what creativecommons.org says. Please read both the GPL and the page I linked before lecturing me, thanks.

Please show me where in any version of GPL that anything licensed under a version of the GPL is also automatically licensed under any other version, without express statement of the copyright holder. GNU certainly encourages the "or any later version" clause, but it is not a requirement, and if it is not included, later versions of the GPL are not applicable. It is the same with any other license agreement. Because that is not how copyright law works. You don't get to decide things for other people because you misunderstand the license and the law.

> Whatever but please fix the mess you created when importing translations that were under a wrong license which, by your own account, is not allowed. UBPorts tagged the sources as 4.0, then people contributed under that assumption.

The more time I have to spend responding to your rudeness and arrogance about licenses, the less time I have to try and fix anything. If you're not going to be helpful then don't say anything. Your attempts to place blame on me or anyone else do not help with anything, and as I already explained, I wasn't even aware of any CC-BY-SA-4.0 thing until today.

**Comment by KAMiKAZOW** [comment]
OK, I fixed my mistake. CC-BY-SA 4.0 now.

**Comment by dobey** [comment]
No, this is still wrong. We are not changing the licenses of other files. Thank you for making me aware of the issue with the UBports Weblate licensing. The correct solution is not this, though. I will deal with the problem in the correct way, which doesn't involve changing the license of something we do not hold the copyright of. Please do not reopen this or make another PR with the same changes. Thanks.

**Comment by Flohack74** [comment]
@KAMiKAZOW I will remove the license display from Weblate. Its not that this entry "conflicts" or "contradicts" anything. Weblate does not determine the license, nor can it overrule anything defined in the source.
Weblate has a convenience function to display a license, whatever that is. IMHO this is not legally binding, as it is not part of the original file.

**Pull request closed without merging**
