### PR TITLE
Release 2.2.1

### PR DESCRIPTION
**Pull request by dobey**

### CODE REVIEW

**Comment by KAMiKAZOW** [comment]
> we do not have permissions to change any existing licenses for which Canonical is the copyright holder

You should have thought of that when you imported updated translations under that license but  luckily what you claim is wrong: https://creativecommons.org/about/cclicenses/

ShareAlike means "If you remix, adapt, or build upon the material, you must license the modified material under identical terms." Non-ShareAlike means that this is not required. CC-BY-SA-4.0 for everything is therefore fine.

**Comment by KAMiKAZOW** [comment]
> There's no need for your rudeness.

I was under the impression you were rude to me when trying to lecturing me in a condescending tone and then I "returned the favor".

>  In any case, it doesn't make your claims any more fact 

The translations you imported are tagged CC-BY-SA 4.0 over there on UBPorts's Weblate. Isn't that a fact?

**Comment by dobey** [comment]
> I was under the impression you were rude to me when trying to lecturing me in a condescending tone and then I "returned the favor".

I was not, but you are welcome to attempt to point to some sort of proof. I merely explained that artwork and translations are not the same thing and are under different licenses, and that we do not hold the copyright on the artwork. But you keep attacking me, just like you did with the previous PRs I made to add the missing COPYING file for the LGPL3 license as it is presented as an addendum, versus LGPL 2.1 which is complete.

> The translations you imported are tagged CC-BY-SA 4.0 over there on UBPorts's Weblate. Isn't that a fact?

No. It is only true for some subset of translations, and that is irrelevant to your claims regarding the text and versioning of licenses themselves. If I release an image under CC-BY 3.0, you cannot  take it and claim it is a CC-BY-SA 4.0 artwork. You can include it in a derivative work which you might license under CC-BY-SA 4.0, but the original work is still CC-BY 3.0. You don't get to determine the license of the original work, only of the derived work.

**Comment by bhush9** [comment]
Now that assets in question is removed we can merge this.

**Review by bhush9 — DISMISSED** [review]

**Comment by dobey** [comment]
> I hope we can reset our standing towards each other to before this.

Please, when you notice something in the future, ping me directly to ask if I'm aware of it, so we can discuss before, as political/social issues are not trivial things to deal with in a simple and unexpected PR, particularly for something that's been in the tree for nearly three months and already in a release for two.

As for the CC-BY 3.0 things, #117 is merged now, to remove those things. And as Florian stated at https://github.com/maliit/keyboard/pull/116#issuecomment-1085205589 it is a Weblate configuration issue which causes confusion, and the license for translations is the same the project being translated. So I'd like to get this merged, so I can tag the releases, and get an update out on the blog.

Thanks.

**Pull request merged**
