### PR TITLE
Fix the build of unit tests and enable them by default

### LINKED ISSUE #7: unit tests cannot be build (and run)
I'm trying to compile this for Alpine Linux/postmarketOS, but am having some issues.

I have maliit-framework installed including the `-dev` package for it which contains the header files, cmake files and pkconfig files. However, while compiling maliit-keyboard it complains that it can't find `maliit/plugins/abstractinputmethodhost.h`.

```
/home/bart/Documents/Git/alpine/aports/testing/maliit-keyboard/src/keyboard-99cd3f439b9504881027ce1b95f8eaa89881e027/tests/unittests/common/inputmethodhostprobe.h:35:10: fatal error: maliit/plugins/abstractinputmethodhost.h: No such file or directory
   35 | #include <maliit/plugins/abstractinputmethodhost.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Seems CMake did find the package so I'm not sure why this is happening, `/usr/include/maliit-2/maliit/plugins/abstractinputmethodhost.h` is available.

### PR DESCRIPTION
**Pull request by dobey**
Fixes #7

### CODE REVIEW

**Comment by dobey** [comment]
I've made this as a draft for the moment, as I would like to figure out why the ut_editor tests needed adjusting and why the skipped test isn't passing. And the tests seem to pass without these changes, in [lomiri-keyboard on Ubuntu Touch](https://ci.ubports.com/blue/organizations/jenkins/UBportsCore%2Flomiri-keyboard/detail/ubports%2Fxenial/12/pipeline/26) still.

**Comment by dobey** [comment]
Setting this as ready, and we can figure out the need to skip the test later I guess, as at least this is better than the current situation with no tests at all.

**Comment by JamiKettunen** [comment]
A new issue should be created for the test which is skipped so it isn't forgotten about :)

**Comment by sunweaver** [comment]
@JamiKettunen @dobey I will pull the patches from this PR over into the maliit-keyboard 2.2.1.1-1 upload to Debian. @dobey: Thanks for working on this.

**Review by jpetersen — APPROVED** [review]

**Comment by dobey** [comment]
> A new issue should be created for the test which is skipped so it isn't forgotten about :)

I have now opened #142 as this PR has been merged.

**Pull request merged**
