### PR TITLE
Delete COPYING

### PR DESCRIPTION
**Pull request by KAMiKAZOW**
#61 was wrong. The LGPL is a full license, not just a set of exceptions. Maliit Keyboard is not under GPL. Shipping the GPL just adds confusion.

### CODE REVIEW

**Review by dobey — CHANGES_REQUESTED** [review]
No, this is not true. The LGPL v3 explicitly states, as you can read in [COPYING.LGPL](https://github.com/maliit/keyboard/blob/master/COPYING.LGPL), the following, and does not include the full text of the GPLv3 which the _additional permissions_ listed in the LGPLv3 extend:

```
  This version of the GNU Lesser General Public License incorporates
the terms and conditions of version 3 of the GNU General Public
License, supplemented by the additional permissions listed below.
```

**Comment by KAMiKAZOW** [comment]
I feel dumb. WTF happened to the long LGPL text I definitively read a few years ago?

**Comment by dobey** [comment]
> I feel dumb. WTF happened to the long LGPL text I definitively read a few years ago?

You perhaps were reading an LGPLv2.1 file (maliit/framework is LGPLv2.1), which sparked some confusion when I opened the PR to add COPYING there, as I'd forgotten that it didn't need both, since I've been working with LGPLv3 only things for so long. No worries though. I hope it's all clear now. :)

**Comment by KAMiKAZOW** [comment]
Could have sworn I've also read a long version of the LGPL 3.0 but perhaps it was an unofficial merged text. I don't know. Sorry for causing confusion.

**Pull request closed without merging**
