### PR TITLE
Remove links to dead mailing list and domain

### PR DESCRIPTION
**Pull request by dobey**

### CODE REVIEW

**Comment by aleixpol** [comment]
I'm pretty sure there needs to be a way to contact the author. Is openismus not a thing anymore?

**Comment by dobey** [comment]
> I'm pretty sure there needs to be a way to contact the author. Is openismus not a thing anymore?

Openismus was closed in 2014 it seems, and `lists.maliit.org` no longer exists for sure. The "contact" would be via GitHub issues at this point. I don't think we need to have the URL replicated in every source file though.

**Comment by aleixpol** [comment]
I'd say let's add issues? The alternative is nobody being mentioned anywhere as soon as the project is tarballed :/

**Comment by dobey** [comment]
> I'd say let's add issues? The alternative is nobody being mentioned anywhere as soon as the project is tarballed :/

I don't think I understand what the issue is. Having a mailing list address that hasn't worked in years doesn't really mention anyone either. The tarballs are hosted on the github page, so the connection between the tarball and the git repo is quite clear.

**Comment by KAMiKAZOW** [comment]
If that was the personal e-mail address of an individual that could be used to distinguish copyright ownership from other people with the same name, I'd keep the mail addresses even if they were not working any more.

These, however, are really just for a dead mailing list. IMO those can go.

**Review by jpetersen — APPROVED** [review]

**Pull request merged**
